import modulsweat
aa=modulsweat.Sweat("шалена бджілка","100","рошен")
bb=modulsweat.Sweat("ромашка","200","світоч")
cc=modulsweat.Sweat("джек","300","конті")
aa.SetPrice("400")
aa.SetName("бимбом")
aa.Display()
bb.Display()
print(cc.GetName())
print(cc.GetPrice())
